import "./globals.css";
import Header from "./ui/header";
import Footer from "./ui/footer";

export const metadata = {
  title: "Live Stream Music",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
